version: '3.8'
services:
  flask-app:
    build: 
      context: ./app1
    deploy:
      replicas: 3
  nginx:
    build: 
      context: ./nginx
    ports:
    - "9090:80"
    depends_on:
      - flask-app

      
